# Copyright (c) 2021 Virtuoel. All Rights Reserved.

name: Bug Report
description: File a bug report
title: "[Bug]: Untitled bug report"
labels: [bug]
assignees:
  - Virtuoel
body:
  - type: markdown
    attributes:
      value: "Write a title for your bug report above!\n\n"
  - type: dropdown
    id: mc_version
    attributes:
      label: Minecraft version(s)
      description:  "What Minecraft version(s) did you experience this bug on?\n
      You may select more than one."
      multiple: true
      options:
        - 1.14.4
        - 1.15.2
        - 1.16.5
        - 1.17.1
        - Other (specify below)
    validations:
      required: true
  - type: input
    id: other_mc_version
    attributes:
      label: Minecraft version details
      description: "Fill in if you selected \"Other\" above."
      placeholder: (e.g. 1.17 Snapshot 21w21a, e.g. 1.18 Experimental Snapshot 1)
    validations:
      required: false
  - type: dropdown
    id: mod_loader
    attributes:
      label: Mod loader
      description: What mod loader were you using?
      options:
        - Fabric
        - Forge
    validations:
      required: true
  - type: input
    id: mod_loader_version
    attributes:
      label: Mod loader version
      description: What Forge version or Fabric Loader version (not Fabric API) were you using?
      placeholder: (e.g. Fabric Loader 0.11.6, e.g. Forge 36.1.62)
    validations:
      required: true
  - type: input
    id: fabric_api_version
    attributes:
      label: Fabric API version
      description: "What Fabric API version (not Fabric Loader) were you using?\n
      (Fill in only if you selected Fabric as your mod loader and a mod you're using requires Fabric API)"
      placeholder: (e.g. Fabric API 0.37.0)
    validations:
      required: false
  - type: dropdown
    id: environment
    attributes:
      label: In what environment did the problem occur?
      options:
        - My singleplayer world
        - My singleplayer world that I opened to LAN
        - A singleplayer world opened to LAN that I was connected to
        - A multiplayer server that I was connected to
        - My multiplayer server that I was running
        - "Other (specify in \"What went wrong?\" section)"
    validations:
      required: true
  - type: textarea
    id: the_problem
    attributes:
      label: What went wrong? (Crash logs don't go here)
      description: "What did you expect to happen, and what happened instead?\n
      (Also, describing steps on how to reproduce the issue will help us fix the problem faster!)"
      placeholder: Tell us what you saw!
    validations:
      required: true
  - type: textarea
    id: other_mods
    attributes:
      label: Full list of installed mods
      description: "What mods were you running at the time? (Make sure to include their version numbers, including the version of this mod!)\n
      (Depending on which mod loader you're using and which launcher you start the game with, sometimes the launcher's logs contain the mod list which can easily be copied and pasted.)"
      placeholder: Put your full mod list here!
    validations:
      required: true
  - type: dropdown
    id: had_crash
    attributes:
      label: Did the problem cause the game to crash?
      options:
        - Yes. (paste crash report below)
        - No.
    validations:
      required: true
  - type: textarea
    id: crash_logs
    attributes:
      label: Full crash report contents (if you experienced a crash)
      description: "Crash report files are typically found within the `.minecraft/crash-reports/` folder in a file with a name similar to `crash-20xx-xx-xx_xx.xx.xx-client.txt`.\n
      If there are multiple, make sure to select the one that corresponds to when you crashed (possibly the most recent file).\n
      Please copy the full contents of the crash report and paste it under the `<p>` line in the box below."
      value: "<details>\n<summary>Crash report output:</summary>\n<p>\n\n"

